# Generated by Django 3.0.2 on 2020-04-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20200406_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active',
            new_name='active',
        ),
    ]
