# Generated by Django 3.0.2 on 2020-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20200429_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='schdule_date',
            field=models.DateTimeField(null=True),
        ),
    ]
