# Generated by Django 3.0.2 on 2020-04-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_todo_schdule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='schdule_date',
            new_name='schedule_date',
        ),
    ]
