# Generated by Django 3.0.2 on 2020-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_auto_20200429_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
